"""Constants for the Sky Remote integration."""

DOMAIN = "sky_remote"
DEFAULT_PORT = 8091
MDNS_SERVICE_TYPE = "_rdk-rics._tcp.local."

# Verified working key names (tested against real Sky STB)
# Source: VAa Dart enum in APK + brute-tested box extras
VERIFIED_KEYS: list[str] = [
    # Navigation & Selection
    "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight",
    "Enter", "Backspace", "Dismiss", "Home",
    # Menu & Information
    "AccessMenu", "Info", "Option", "Search", "Settings",
    # Channel & Volume
    "ChannelUp", "ChannelDown",
    "VolumeUp", "VolumeDown", "VolumeMute",
    # Playback
    "MediaPlay", "MediaRecord", "MediaRewind", "MediaFastForward",
    # Power & Source
    "Power", "Source", "Plus",
    # Digits
    "Digit0", "Digit1", "Digit2", "Digit3", "Digit4",
    "Digit5", "Digit6", "Digit7", "Digit8", "Digit9",
    # Colour buttons
    "Red", "Green", "Yellow", "Blue",
]

# Auth token salt (from APK binary analysis)
AUTH_SALT = b"biT43y"

# Embedded certificates for mTLS
CLIENT_KEY_PEM = """\
-----BEGIN EC PARAMETERS-----
BggqhkjOPQMBBw==
-----END EC PARAMETERS-----
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIC6SaKhxcT/GDHtglEHWdhuczo5CN9aUPqcvBt06nTNqoAoGCCqGSM49
AwEHoUQDQgAEOTYzQwBDZtPe22jtWJfqPf4FPwevN/s4pSMSVPStJvqpnM5CFFzi
p8JGCNEvGnj/9rhRy7Pw2fTkAjjDOTHspA==
-----END EC PRIVATE KEY-----
"""

CLIENT_CERT_PEM = """\
-----BEGIN CERTIFICATE-----
MIICqzCCAlGgAwIBAgIUBpcPWUFHiLVOTsI1KdIWQiAHwKcwCgYIKoZIzj0EAwIw
JDEiMCAGA1UEAwwZQ29tY2FzdCBSREsgRDJEIEVDQyBJQ0EgMTAeFw0yNTA1Mjgx
NTU1MDVaFw0yNjA1MjgxNzU1MDVaMIGfMTIwMAYKCZImiZPyLGQBAQwiMURKNHhT
M1J2OUQzVkpOdEpxN1FEcVVrenhzWGtacjNyeTEUMBIGA1UEAwwLc2t5LnhjYWwu
dHYxEDAOBgNVBAsMB1hmaW5pdHkxEDAOBgNVBAoMB0NvbWNhc3QxDjAMBgNVBAcM
BUVzc2V4MRIwEAYDVQQIDAlCcmVudHdvb2QxCzAJBgNVBAYTAkdCMFkwEwYHKoZI
zj0CAQYIKoZIzj0DAQcDQgAEOTYzQwBDZtPe22jtWJfqPf4FPwevN/s4pSMSVPSt
JvqpnM5CFFzip8JGCNEvGnj/9rhRy7Pw2fTkAjjDOTHspKOB5DCB4TA+BgNVHREE
NzA1gRppcGNvbnRyb2wtcmljc0ByZGsuc2VydmljZYEXc2t5LXNvZnRyZW1vdGVA
cmRrLnVzZXIwCwYDVR0PBAQDAgWgMBMGA1UdJQQMMAoGCCsGAQUFBwMCMAwGA1Ud
EwEB/wQCMAAwHwYDVR0jBBgwFoAUcE8ZliAdb1LD6xZrZrpo6oI4Q64wLwYIKwYB
BQUHAQEEIzAhMB8GCCsGAQUFBzABhhNodHRwOi8vb2NzcC54cGtpLmlvMB0GA1Ud
DgQWBBR1S6mo2MU0DG/Di7CBdbXw+vKtoTAKBggqhkjOPQQDAgNIADBFAiAG0zGM
btylRpcpcd3QexdI6B+PZ4pTmOVoFpUo4LVb0QIhAJGIPyF9DagqIYcUns8ZseRJ
wjP5FMrLKuNUQfELO2nv
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBsjCCAVegAwIBAgIUBzGYtexCSQ6tKXt7/gD6qKRCtk8wCgYIKoZIzj0EAwIw
IzEhMB8GA1UEAwwYQ29tY2FzdCBSREsgRDJEIEVDQyBSb290MCAXDTI0MDIyODE5
MjYwMVoYDzIwNTQwMjIwMTkxMzQxWjAkMSIwIAYDVQQDDBlDb21jYXN0IFJESyBE
MkQgRUNDIElDQSAxMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEWbM/CXd9amo4
t5pmcJZGbhxuZP3e2EOTNu9j5nWuSlwz3bQ/cqYCJi23YFQFAntxqhcwCC3Vi4v0
ZMcXYtMULKNmMGQwEgYDVR0TAQH/BAgwBgEB/wIBADAfBgNVHSMEGDAWgBSG/d1b
GTbWy61CNEUbH76lmvZn1DAdBgNVHQ4EFgQUcE8ZliAdb1LD6xZrZrpo6oI4Q64w
DgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMCA0kAMEYCIQDzM8oTpL6AC5Gwd1d/
fb94ipyQgswBbffeHZTURsPw8gIhALGKUGBLCAtwdXLiqMCeTBesliac+yZR3b/D
J3MEo+oy
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIIBsDCCAVagAwIBAgIUMi5R+Ioo/aAFMjepe9XGPrUMtxowCgYIKoZIzj0EAwIw
IzEhMB8GA1UEAwwYQ29tY2FzdCBSREsgRDJEIEVDQyBSb290MCAXDTI0MDIyODE5
MTM0MloYDzIwNTQwMjIwMTkxMzQxWjAjMSEwHwYDVQQDDBhDb21jYXN0IFJESyBE
MkQgRUNDIFJvb3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQM6kHWOmISlcpU
TE+nxDShDp/QDmucVh0wWpHNFu/NDXRcPwNd6LPeShyM5TlBcUFzjgI7qsFqoDpW
eB0jKk8zo2YwZDASBgNVHRMBAf8ECDAGAQH/AgEBMB8GA1UdIwQYMBaAFIb93VsZ
NtbLrUI0RRsfvqWa9mfUMB0GA1UdDgQWBBSG/d1bGTbWy61CNEUbH76lmvZn1DAO
BgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDSAAwRQIgUTTH19CiP120ax8p3dYO
IPbVsSWOfz01ZKit6T0TXncCIQDm9btfvUhVRyhHEScynV1v95q4podgkTTVJawo
GrD1ZA==
-----END CERTIFICATE-----
"""

CA_CERT_PEM = """\
-----BEGIN CERTIFICATE-----
MIIBsDCCAVagAwIBAgIUMi5R+Ioo/aAFMjepe9XGPrUMtxowCgYIKoZIzj0EAwIw
IzEhMB8GA1UEAwwYQ29tY2FzdCBSREsgRDJEIEVDQyBSb290MCAXDTI0MDIyODE5
MTM0MloYDzIwNTQwMjIwMTkxMzQxWjAjMSEwHwYDVQQDDBhDb21jYXN0IFJESyBE
MkQgRUNDIFJvb3QwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQM6kHWOmISlcpU
TE+nxDShDp/QDmucVh0wWpHNFu/NDXRcPwNd6LPeShyM5TlBcUFzjgI7qsFqoDpW
eB0jKk8zo2YwZDASBgNVHRMBAf8ECDAGAQH/AgEBMB8GA1UdIwQYMBaAFIb93VsZ
NtbLrUI0RRsfvqWa9mfUMB0GA1UdDgQWBBSG/d1bGTbWy61CNEUbH76lmvZn1DAO
BgNVHQ8BAf8EBAMCAYYwCgYIKoZIzj0EAwIDSAAwRQIgUTTH19CiP120ax8p3dYO
IPbVsSWOfz01ZKit6T0TXncCIQDm9btfvUhVRyhHEScynV1v95q4podgkTTVJawo
GrD1ZA==
-----END CERTIFICATE-----
"""
